# Generated by Django 2.1.1 on 2018-10-14 13:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordenador', '0001_initial'),
        ('curso', '0001_initial'),
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='ABERTA', max_length=7)),
                ('planoDeEnsino', models.TextField()),
                ('cargaHoraria', models.IntegerField()),
                ('competencias', models.CharField(max_length=30)),
                ('habilidade', models.CharField(max_length=30)),
                ('ementa', models.CharField(max_length=30)),
                ('conteudoProgramatico', models.CharField(max_length=30)),
                ('bibliografiaBasica', models.CharField(max_length=30)),
                ('bibliografiaComplementar', models.CharField(max_length=30)),
                ('percentualPatrico', models.IntegerField()),
                ('percentualTeorico', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaOferatada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtInicioMatricula', models.DateField(default=None)),
                ('dtFimMatricula', models.DateField(default=None)),
                ('ano', models.IntegerField()),
                ('semetre', models.IntegerField()),
                ('Turma', models.CharField(max_length=1)),
                ('metodologia', models.CharField(default=None, max_length=250)),
                ('recursos', models.CharField(default=None, max_length=100)),
                ('criterioAvaliacao', models.CharField(default=None, max_length=100)),
                ('planoDeAulas', models.CharField(default=None, max_length=100)),
                ('id_coordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coordenador.Coordenador')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.Curso')),
                ('id_disciplina', models.ForeignKey(on_delete=classmethod, to='disciplina.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtSolicitacao', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Solicitada', max_length=10)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.Aluno')),
                ('id_coordernador', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coordenador.Coordenador')),
                ('id_disciplina', models.ForeignKey(on_delete=classmethod, to='disciplina.Disciplina')),
            ],
        ),
    ]
