# Generated by Django 2.1.1 on 2018-10-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Login', models.CharField(max_length=100, unique=True)),
                ('Senha', models.CharField(max_length=250)),
                ('DtExpiracao', models.DateField(default='01/01/1900')),
            ],
        ),
    ]
