# Generated by Django 2.1.1 on 2018-11-03 16:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('dtExpiracao', models.DateField(default=datetime.date(1900, 1, 1))),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('celular', models.CharField(max_length=14, unique=True)),
                ('ra', models.IntegerField()),
                ('foto', models.CharField(blank=True, default=None, max_length=350)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(default=None, max_length=255)),
                ('conteudo', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=15)),
                ('extrar', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeVinculada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=4)),
                ('status', models.CharField(max_length=15)),
                ('dtInicioRespostas', models.DateField()),
                ('dtFimRespostas', models.DateField()),
                ('id_atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('celular', models.CharField(max_length=14, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='ABERTA', max_length=7)),
                ('planoDeEnsino', models.TextField()),
                ('cargaHoraria', models.IntegerField()),
                ('competencias', models.CharField(max_length=30)),
                ('habilidade', models.CharField(max_length=30)),
                ('ementa', models.CharField(max_length=30)),
                ('conteudoProgramatico', models.CharField(max_length=30)),
                ('bibliografiaBasica', models.CharField(max_length=30)),
                ('bibliografiaComplementar', models.CharField(max_length=30)),
                ('percentualPatrico', models.IntegerField()),
                ('percentualTeorico', models.IntegerField()),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Coordenador')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaOferatada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtInicioMatricula', models.DateField(default=None)),
                ('dtFimMatricula', models.DateField(default=None)),
                ('ano', models.IntegerField()),
                ('semetre', models.IntegerField()),
                ('Turma', models.CharField(max_length=1)),
                ('metodologia', models.CharField(default=None, max_length=250)),
                ('recursos', models.CharField(default=None, max_length=100)),
                ('criterioAvaliacao', models.CharField(default=None, max_length=100)),
                ('planoDeAulas', models.CharField(default=None, max_length=100)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Coordenador')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Curso')),
                ('disciplina', models.ForeignKey(on_delete=classmethod, to='core.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('resposta', models.CharField(max_length=250)),
                ('dtEntrega', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Entregue', max_length=9)),
                ('nota', models.FloatField(default=None)),
                ('dtAvaliacao', models.DateField(default=None)),
                ('obs', models.CharField(default=None, max_length=150)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aluno')),
                ('id_atividadeVinculada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AtividadeVinculada')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=150)),
                ('conteudo', models.CharField(max_length=250)),
                ('status', models.CharField(default='Enviado', max_length=10)),
                ('dtEnvio', models.DateField(default=django.utils.timezone.now)),
                ('dtResposta', models.DateField()),
                ('resposta', models.CharField(max_length=250)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('celular', models.CharField(max_length=14, unique=True)),
                ('apelido', models.CharField(max_length=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtSolicitacao', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Solicitada', max_length=10)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aluno')),
                ('coordernador', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Coordenador')),
                ('disciplina', models.ForeignKey(on_delete=classmethod, to='core.Disciplina')),
            ],
        ),
        migrations.AddField(
            model_name='mensagem',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Professor'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Professor'),
        ),
        migrations.AddField(
            model_name='disciplinaoferatada',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Professor'),
        ),
        migrations.AddField(
            model_name='atividadevinculada',
            name='id_disciplinaOfertada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DisciplinaOferatada'),
        ),
        migrations.AddField(
            model_name='atividadevinculada',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Professor'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Professor'),
        ),
    ]
