# Generated by Django 2.1.1 on 2018-10-21 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dtExpiracao',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
    ]
