# Generated by Django 2.1.1 on 2018-10-14 13:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(default=None, max_length=255)),
                ('conteudo', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=15)),
                ('extrar', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeVinculada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=4)),
                ('status', models.CharField(max_length=15)),
                ('dtInicioRespostas', models.DateField()),
                ('dtFimRespostas', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('resposta', models.CharField(max_length=250)),
                ('dtEntrega', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Entregue', max_length=9)),
                ('nota', models.FloatField(default=None)),
                ('dtAvaliacao', models.DateField(default=None)),
                ('obs', models.CharField(default=None, max_length=150)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.Aluno')),
                ('id_atividadeVinculada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atividade.AtividadeVinculada')),
            ],
        ),
    ]
