# Generated by Django 2.1.1 on 2018-10-14 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplina', '0001_initial'),
        ('professor', '0001_initial'),
        ('atividade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrega',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.Professor'),
        ),
        migrations.AddField(
            model_name='atividadevinculada',
            name='id_atividade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atividade.Atividade'),
        ),
        migrations.AddField(
            model_name='atividadevinculada',
            name='id_disciplinaOfertada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplina.DisciplinaOferatada'),
        ),
        migrations.AddField(
            model_name='atividadevinculada',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.Professor'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='id_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.Professor'),
        ),
    ]
